main:
  - name: Publications
    url: https://team-aprl.github.io/publications.html
    weight: 20
  - name: Talks
    url: '#talks'
    weight: 30
  - name: Awards
    url: '#awards'
    weight: 32
  - name: Funding
    url: https://team-aprl.github.io/projects.html
    weight: 25
  - name: Service
    url: '#academic-service'
    weight: 35
  - name: Teaching
    url: https://team-aprl.github.io/teaching.html
    weight: 40
  - name: Projects
    url: '#personal-projects'
    weight: 45
  - name: Gallery
    url: '#gallery'
    weight: 47
  - name: Essays
    url: /essays/
    weight: 50
  - name: CV
    url: https://drive.google.com/drive/folders/1_0XFI8jedwYIr4QIIQ17cvAXhwOPRSrd
    weight: 60
